-- AlterTable
ALTER TABLE "product_metrics" ADD COLUMN     "add_to_cart_rate" DECIMAL(10,8),
ADD COLUMN     "aov" DECIMAL(10,2),
ADD COLUMN     "ctor" DECIMAL(10,8),
ADD COLUMN     "gmv_with_subsidy" DECIMAL(15,2),
ADD COLUMN     "gmv_with_tax" DECIMAL(15,2),
ADD COLUMN     "items_sold" INTEGER,
ADD COLUMN     "refunded_customers" INTEGER,
ADD COLUMN     "refunded_items" INTEGER,
ADD COLUMN     "refunds" DECIMAL(15,2),
ADD COLUMN     "shipping_fees" DECIMAL(15,2),
ADD COLUMN     "sku_orders" INTEGER,
ADD COLUMN     "tax" DECIMAL(15,2),
ADD COLUMN     "unique_add_to_cart_rate" DECIMAL(10,8),
ADD COLUMN     "unique_add_to_cart_users" INTEGER,
ADD COLUMN     "unique_clicks" INTEGER,
ADD COLUMN     "unique_ctor" DECIMAL(10,8),
ADD COLUMN     "unique_ctr" DECIMAL(10,8),
ADD COLUMN     "unique_impressions" INTEGER;
